ALTER TABLE uploads ADD COLUMN lang VARCHAR(10) NOT NULL DEFAULT 'en';
ALTER TABLE settings ADD COLUMN enabled_languages VARCHAR(100) NOT NULL DEFAULT 'en,sv';
ALTER TABLE settings ADD COLUMN language VARCHAR(10) NOT NULL DEFAULT 'en';
